### ISSUE TITLE
add dashbot to alexa

### ISSUE THREAD

**Issue by hyzhak** [internetarchive/internet-archive-voice-apps#379]

**Comment by hyzhak** [comment]
after tried to connect by:
https://www.dashbot.io/docs/alexa/lambdav2/

got:

> TypeError: Converting circular structure to JSON
>     at JSON.stringify (<anonymous>)
>     at module.exports (/internet-archive-google-action/functions/node_modules/dashbot/src/make-request.js:13:16)
>     at internalLogIncoming (/internet-archive-google-action/functions/node_modules/dashbot/src/dashbot-amazon-alexa.js:23:12)
>     at DashBotBase.DashBotAmazonAlexa.that.logIncoming (/internet-archive-google-action/functions/node_modules/dashbot/src/dashbot-amazon-alexa.js:51:12)
>     at Object.setupAspectJoinpoint (/internet-archive-google-action/functions/node_modules/dashbot/src/dashbot-amazon-alexa.js:151:32)
>     at callAround (/internet-archive-google-action/functions/node_modules/meld/meld.js:242:20)
>     at callNext (/internet-archive-google-action/functions/node_modules/meld/meld.js:221:8)
>     at Advisor._callAroundAdvice (/internet-archive-google-action/functions/node_modules/meld/meld.js:290:11)
>     at Object.Advisor.advised.advised [as handler] (/internet-archive-google-action/functions/node_modules/meld/meld.js:130:33)
>     at LambdaServer.invoke (/internet-archive-google-action/functions/node_modules/bespoken-tools/lib/client/lambda-server.js:94:52)
>

**Comment by hyzhak** [comment]
here is related issue https://github.com/actionably/dashbot/issues/28
