### ISSUE TITLE
Error while setting up the project

### ISSUE THREAD

**Issue by anuragiiits** [internetarchive/internet-archive-voice-apps#452]
Hi, I have followed the setup instructions from README, and I am able to start the server with `npm start` and exposed my local server globally using **ngrok**. However, if I open the link [http://localhost:5000/internetarchive-f56c8/us-central1/assistant](http://localhost:5000/internetarchive-f56c8/us-central1/assistant), or whenever Dialogflow makes a request to my server, it throws up the following error:

> error: TypeError: Cannot read property 'type' of undefined
>     at module.exports (C:\Users\anura\Documents\gsoc\internet-archive-voice-apps\internet-archive-voice-apps\functions\src\platform\assistant\middlewares\log-empty-session-data.js:14:57)
>     at Function.<anonymous> (C:\Users\anura\Documents\gsoc\internet-archive-voice-apps\internet-archive-voice-apps\functions\node_modules\actions-on-google\dist\service\dialogflow\dialogflow.js:123:32)
>     at Generator.next (<anonymous>)
>     at fulfilled (C:\Users\anura\Documents\gsoc\internet-archive-voice-apps\internet-archive-voice-apps\functions\node_modules\actions-on-google\dist\service\dialogflow\dialogflow.js:19:58)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> info: Execution took 1010 ms, user function completed successfully

and **ngrok** gives `500 Internal Server Error`

And when I visit http://localhost:5000/internetarchive-f56c8/us-central1/assistant then following json shows up

// http://localhost:5000/internetarchive-f56c8/us-central1/assistant

{
  "error": "Cannot read property 'type' of undefined"
}

I tried looking at previous issues but couldn't find a solution to this. Please help me by telling where I might have gone wrong. Is it due to some version conflict of any tool?

**Comment by anuragiiits** [comment]
Same issue as you addressed in https://github.com/internetarchive/internet-archive-voice-apps/issues/457

**Comment by vedang14** [comment]
I would like to work on this issue @hyzhak , and would like to improve over README.md file instructions
